"use client";

import { useEffect, useState, type FormEvent } from "react";
import { AlertTriangle, LockKeyhole, ShieldCheck } from "lucide-react";
import { splitList } from "@/src/lib/validation/product";

type Settings = { enabled: boolean; simulation_completed_at?: string; minimum_match: number; daily_limit: number; weekly_limit: number; company_daily_limit: number; maximum_job_age_hours: number; company_whitelist: string[]; company_blacklist: string[] };
const defaults: Settings = { enabled: false, minimum_match: 85, daily_limit: 10, weekly_limit: 50, company_daily_limit: 2, maximum_job_age_hours: 72, company_whitelist: [], company_blacklist: [] };

export function AutomationSettings() {
  const [settings, setSettings] = useState<Settings>(); const [policyEnabled, setPolicyEnabled] = useState(false); const [message, setMessage] = useState("Loading safety settings…");
  async function load() { const response = await fetch("/api/settings/automation"); const body = await response.json() as { settings?: Settings; policyEnabled?: boolean; error?: string }; if (response.ok) { setSettings({ ...defaults, ...(body.settings ?? {}) }); setPolicyEnabled(Boolean(body.policyEnabled)); setMessage(""); } else setMessage(body.error ?? "Could not load settings."); }
  useEffect(() => { void fetch("/api/settings/automation").then(async (response) => ({ response, body: await response.json() as { settings?: Settings; policyEnabled?: boolean; error?: string } })).then(({ response, body }) => { if (response.ok) { setSettings({ ...defaults, ...(body.settings ?? {}) }); setPolicyEnabled(Boolean(body.policyEnabled)); setMessage(""); } else setMessage(body.error ?? "Could not load settings."); }); }, []);
  async function simulate() { setMessage("Running safety-rule simulation…"); const response = await fetch("/api/settings/automation/simulate", { method: "POST" }); const body = await response.json() as { error?: string }; if (response.ok) { await load(); setMessage("Simulation passed: sensitive, missing, and CAPTCHA cases all stopped correctly."); } else setMessage(body.error ?? "Simulation failed."); }
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setMessage("Saving…"); const payload = { enabled: form.get("enabled") === "on", minimumMatch: Number(form.get("minimumMatch")), dailyLimit: Number(form.get("dailyLimit")), weeklyLimit: Number(form.get("weeklyLimit")), companyDailyLimit: Number(form.get("companyDailyLimit")), maximumJobAgeHours: Number(form.get("maximumJobAgeHours")), companyWhitelist: splitList(String(form.get("companyWhitelist") ?? "")), companyBlacklist: splitList(String(form.get("companyBlacklist") ?? "")) }; const response = await fetch("/api/settings/automation", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json() as { error?: string }; if (response.ok) { await load(); setMessage("Automation settings saved."); } else setMessage(body.error ?? "Could not save settings."); }
  if (!settings) return <article className="product-card" role="status">{message}</article>;
  return <form className="settings-grid" onSubmit={save}><article className="product-card safety-card"><div className="card-title"><ShieldCheck /><div><h2>Application safety gate</h2><p>Both server policy and your explicit preference must allow submission.</p></div></div><div className="check-row"><span><strong>Safety simulation</strong><small>{settings.simulation_completed_at ? `Passed ${new Date(settings.simulation_completed_at).toLocaleString()}` : "Not run yet"}</small></span><button className="secondary-button" type="button" onClick={simulate}>Run simulation</button></div><label className={`check-row ${!settings.simulation_completed_at || !policyEnabled ? "disabled" : ""}`}><input aria-label="Enable automatic submission" name="enabled" type="checkbox" defaultChecked={settings.enabled} disabled={!settings.simulation_completed_at || !policyEnabled} /><span><strong>Enable automatic submission</strong><small>{policyEnabled ? "Sensitive answers, CAPTCHA, OTP, login, and unsupported flows still stop." : "Disabled by server policy."}</small></span></label>{settings.enabled ? <p className="inline-warning"><AlertTriangle size={16} /> Automatic submission is enabled within the limits below.</p> : <p className="inline-safe"><LockKeyhole size={16} /> Submissions are blocked.</p>}</article>
    <article className="product-card profile-form"><h2>Eligibility and hard limits</h2><div className="form-grid"><label>Minimum match<input name="minimumMatch" type="number" min="0" max="100" defaultValue={settings.minimum_match} /></label><label>Maximum job age (hours)<input name="maximumJobAgeHours" type="number" min="1" max="720" defaultValue={settings.maximum_job_age_hours} /></label><label>Daily limit<input name="dailyLimit" type="number" min="1" max="25" defaultValue={settings.daily_limit} /></label><label>Weekly limit<input name="weeklyLimit" type="number" min="1" max="100" defaultValue={settings.weekly_limit} /></label><label>Per-company daily limit<input name="companyDailyLimit" type="number" min="1" max="5" defaultValue={settings.company_daily_limit} /></label></div><label>Company allowlist<input name="companyWhitelist" defaultValue={settings.company_whitelist.join(", ")} placeholder="Empty means no allowlisted company" /></label><label>Company blocklist<input name="companyBlacklist" defaultValue={settings.company_blacklist.join(", ")} /></label><button type="submit">Save safety settings</button><p className="form-status" role="status">{message}</p></article></form>;
}
